### ISSUE TITLE
 ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: <tf.Tensor 'targets:0' shape=(32, 300) dtype=int64>

### ISSUE THREAD

**Issue by dongTaylor** [stanleylsx/entity_extractor_by_ner#11]
用下载的代码源码改为训练模式训练，报错
ValueError: in user code:

    /home/ml/entity_extractor_by_ner/engines/model.py:34 call  *

 ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: <tf.Tensor 'targets:0' shape=(32, 300) dtype=int64>

**Comment by stanleylsx** [comment]
> 用下载的代码源码改为训练模式训练，报错
> ValueError: in user code:
> 
> ```
> /home/ml/entity_extractor_by_ner/engines/model.py:34 call  *
> ```
> 
> ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: <tf.Tensor 'targets:0' shape=(32, 300) dtype=int64>

已修复

**Comment by guo-xiaomeng** [comment]
同样遇到这个问题，没有解决。。。
