### ISSUE TITLE
请教下关系抽取？

### ISSUE THREAD

**Issue by onex7777** [stanleylsx/entity_extractor_by_ner#12]
您的程序目前实现的是实体抽取，没有关系抽取？

**Comment by stanleylsx** [comment]
> 您的程序目前实现的是实体抽取，没有关系抽取？

关系抽取的项目有规划中，目前还没有写。

**Comment by onex7777** [comment]
谢谢你!代码太有作用了

发送自 Windows 10 版邮件应用

发件人: lishouxian
发送时间: 2021年4月25日 19:15
收件人: StanleyLsx/entity_extractor_by_ner
抄送: wxue1995; Author
主题: Re: [StanleyLsx/entity_extractor_by_ner] 请教下关系抽取？ (#12)

您的程序目前实现的是实体抽取，没有关系抽取？
关系抽取的项目有规划中，目前还没有写。

**Comment by stanleylsx** [comment]
> 您的程序目前实现的是实体抽取，没有关系抽取？

https://github.com/StanleyLsx/relation_extraction
