### ISSUE TITLE
代码有点问题

### ISSUE THREAD

**Issue by CoderBinGe** [stanleylsx/entity_extractor_by_ner#13]
data.py的prepare方法，我输出的X矩阵和y向量都为空

**Comment by StanleyLsx** [comment]
> data.py的prepare方法，我输出的X矩阵和y向量都为空

你用的哪个版本？

**Comment by stanleylsx** [comment]
> data.py的prepare方法，我输出的X矩阵和y向量都为空

你用的哪个版本？描述不清楚我没有办法解决。

**Comment by CoderBinGe** [comment]
[详见colab](https://colab.research.google.com/drive/1E8w13vJ7mAfNC3ziVNIJ8cWtOK51JjDD?usp=sharing)

**Comment by stanleylsx** [comment]
> [详见colab](https://colab.research.google.com/drive/1E8w13vJ7mAfNC3ziVNIJ8cWtOK51JjDD?usp=sharing)

我看了你的代码，是自己片取的项目代码。我只能保证我仓库代码不出问题，你可能需要自己多调试下你的代码。
