### ISSUE TITLE
acc 全为0

### ISSUE THREAD

**Issue by kkxcam** [stanleylsx/entity_extractor_by_ner#14]
![image](https://user-images.githubusercontent.com/35211411/116071582-a6f5f280-a6c0-11eb-8016-76af38139cca.png)
为什么每个实体标签的 acc都为0呢

**Comment by stanleylsx** [comment]
> ![image](https://user-images.githubusercontent.com/35211411/116071582-a6f5f280-a6c0-11eb-8016-76af38139cca.png)
> 为什么每个实体标签的 acc都为0呢

这是个bug，忘记改了。

**Comment by LiAI-tech** [comment]
请问怎么修改呢？

**Comment by stanleylsx** [comment]
每个单独的实体无法提供准确率，准确率直接看每次验证集的综合结果即可。
