### ISSUE TITLE
转换类型有问题

### ISSUE THREAD

**Issue by zhu13818202655** [stanleylsx/entity_extractor_by_ner#16]
tensor_targets = tf.convert_to_tensor(targets, dtype=tf.int32)这里会报错
改成tensor_targets = tf.convert_to_tensor(targets, dtype=tf.int64)就可以使用

**Comment by StanleyLsx** [comment]
这个好像与机器有关，原来我也是写的int64换了公司电脑就不行了，需要改成32。这个问题可能与环境有关。

**Comment by stanleylsx** [comment]
> tensor_targets = tf.convert_to_tensor(targets, dtype=tf.int32)这里会报错
> 改成tensor_targets = tf.convert_to_tensor(targets, dtype=tf.int64)就可以使用

这个好像与环境有关，原来有人说要改成32。
