### ISSUE TITLE
关于数据集标注

### ISSUE THREAD

**Issue by iiixiscientia** [stanleylsx/entity_extractor_by_ner#19]
你好，我想尝试用这个模型来训练自己的训练集，但是我的领域里暂时没有大量的语料库或者词典，所以要自己打标签和BIO标注。请问哪种工具可以把数据集的标签打得和模型中的tokenid、vocabid、dev.csv和train.csv的格式一致？还是需要手动打tag？我的语料都是英文的。

**Comment by stanleylsx** [comment]
> 你好，我想尝试用这个模型来训练自己的训练集，但是我的领域里暂时没有大量的语料库或者词典，所以要自己打标签和BIO标注。请问哪种工具可以把数据集的标签打得和模型中的tokenid、vocabid、dev.csv和train.csv的格式一致？还是需要手动打tag？我的语料都是英文的。

我仓库里面的数据集是公开数据集，如果你要打标可能要去搜一搜打标平台了。
