### ISSUE TITLE
bert模型位置

### ISSUE THREAD

**Issue by lzy0609** [stanleylsx/entity_extractor_by_ner#23]
你好~请问bert模型自动下载，是下载到哪里了呢，我看项目文件里没有呀~

**Comment by lzy0609** [comment]
我看了一下，是不是~\.cache\torch\transformers里面呢~

**Comment by stanleylsx** [comment]
> 我看了一下，是不是~.cache\torch\transformers里面呢~
是的，你ls -mh一下比较大的文件就是预训练模型。
