### ISSUE TITLE
bert

### ISSUE THREAD

**Issue by chenjiawei22** [stanleylsx/entity_extractor_by_ner#24]
你好，能不能先下载好bert使用啊？如果能代码里面应该怎么改？怎么下载会比较快？请大佬赐教

**Comment by stanleylsx** [comment]
> 你好，能不能先下载好bert使用啊？如果能代码里面应该怎么改？怎么下载会比较快？请大佬赐教

可以的，使用transformers包加载本地模型，具体可以参照抱报脸的官网喔。https://huggingface.co/
