### ISSUE TITLE
GPU 使用率

### ISSUE THREAD

**Issue by ancue** [stanleylsx/entity_extractor_by_ner#6]
感谢分享。训练过程中GPU 使用率一直在30%到60%之间，有没有什么办法可以提高？

**Comment by StanleyLsx** [comment]
确实存在这个问题，个人觉得个人从以下几个办法提高gpu的利用率：
1.提高batch的大小，尽可能多用显存
2.减少一些中途的打印输出
3.每个batch开始前，针对每个batch的数据有个shuffle和提取下一个批次的过程，这个部分的数据封装一直没时间改，你可以尝试使用tf.data.Dataset重构下。

**Comment by stanleylsx** [comment]
> 感谢分享。训练过程中GPU 使用率一直在30%到60%之间，有没有什么办法可以提高？

确实存在这个问题，个人觉得个人从以下几个办法提高gpu的利用率：
1.提高batch的大小，尽可能多用显存
2.减少一些中途的打印输出
3.每个batch开始前，针对每个batch的数据有个shuffle和提取下一个批次的过程，这个部分的数据封装一直没时间改，你可以尝试使用tf.data.Dataset重构下。
