### ISSUE TITLE
要是有测试集测试就完美了

### ISSUE THREAD

**Issue by Tony0726** [stanleylsx/entity_extractor_by_ner#9]
因为现在都是训练集的各项指标看起来不错，但是在测试集上效果怎么样也就是泛化性还不是很清楚，不过已经非常好了，万分感谢！

**Comment by stanleylsx** [comment]
> 因为现在都是训练集的各项指标看起来不错，但是在测试集上效果怎么样也就是泛化性还不是很清楚，不过已经非常好了，万分感谢！

测试集可以再在原来的数据集上划分下，然后写个批量跑的代码。感谢您的认可。

**Comment by Tony0726** [comment]
作者您好，我看您的代码，是不是验证集就是我们平常说的测试集，因为好像验证集对于训练是没有影响的（除了early stop），所以starting evaluate model...之后打印出来的衡量指标就是反映模型的泛化性的吧？

**Comment by kkxcam** [comment]
![image](https://user-images.githubusercontent.com/35211411/116071582-a6f5f280-a6c0-11eb-8016-76af38139cca.png)
100%|###############################################################################################| 145/145 [02:04<00:00,  1.16it/s]
label: ORG, precision: 0.883 recall: 0.901 f1: 0.888 accuracy: 0.000 
label: PER, precision: 0.973 recall: 0.969 f1: 0.969 accuracy: 0.000 
label: LOC, precision: 0.936 recall: 0.942 f1: 0.937 accuracy: 0.000 
time consumption:10.39(min), precision: 0.944 recall: 0.949 f1: 0.946 accuracy: 0.993 
saved the new best model with f1: 0.946
epoch:3/300

为什么每个实体标签的 acc都为0呢
